### PR TITLE
ENH: New, expanded panorama demo w/MCP stitching!

### PR DESCRIPTION
**Pull request by JDWarner**
Take a look, @stefanv - the minimum cost path method to stitch images together works _very_ well.

No more need for Enblend!

I limited the long axis on these pictures (which I have listed as CC-BY 4.0 right now, but could be persuaded to move to CC0) to 720 pixels. They're under 2MB in total, and ORB features take about 6 seconds total to extract from either set on my machine.

### CODE REVIEW

**Comment by JDWarner** [comment]
@stefanv if this looks good to you, I think it's ready to merge on my end.

Allowing "sliding" borders for MCP was a capital idea!

**Comment by stefanv** [comment]
This looks great, Josh!  I think it would be good to add a way to export the final image to jpeg.

**Comment by JDWarner** [comment]
Done!

**Comment by JDWarner** [comment]
Don't merge _quite_ yet, I'm going to simplify the MCP path seeds because the sliding border work so well.

**Comment by JDWarner** [comment]
Ruh roh, I found another challenge - to fix it requires tweaking the MCP cost function. Think I've got a fix.

**Comment by JDWarner** [comment]
@stefanv I think my work is done here!

The new cost array building function is necessary. I couldn't find any way to simplify it further. The results are now excellent and robust.

Basically, because the area surrounding the diff intersection was penalized so strongly, if the intersection border wasn't parallel with the top/bottom borders, the minimum-cost paths wer going straight to the closest corner. The new function gives the longer paths appropriate "breaks" in cost to be equally attractive.

**Comment by stefanv** [comment]
Remind me again why the area outside the diff is penalized?

**Comment by JDWarner** [comment]
If not, the MCP finds the trivial solution by skirting the entire diff region.

**Comment by stefanv** [comment]
I guess the question should be whether the correct constant background cost
could save us all the effort.

**Comment by JDWarner** [comment]
No constant background will work this well; in that case you always have a contest between distance from the edge vs. quality of overlap. The path will choose essentially the midpoint between these, often resulting in visible exposure differences from vignetting. Trying to minimize this involves lowering the constant background toward the limit of zero... but you'll never get there; at some point it will snap to the trivial solution.

The only way to make it robustly choose the _best_ path is to eliminate distance from the edge as a factor.

**Comment by stefanv** [comment]
@JDWarner How about if we use a distance transform as computed by ``scipy.ndimage.distance_transform_edt``?

**Comment by JDWarner** [comment]
@stefanv I tried the various distance transforms. The distance function
alone cannot be used, as it makes the incentive to go for the nearest
corner even stronger.

If you forge ahead, they all suffer from two big problems:

* they find the lowest linear distance to the ROI instead of constraining
to lowest _vertical_ distance. As a result, the correction is inaccurate
anywhere the ROI isn't parallel with the border.
* Because of this, things blur together and it's much harder to identify
the regions that need to be excluded from the correction.

It ends up being harder and more complicated than doing it the right way.

@JDWarner <https://github.com/JDWarner> How about if we use a distance
transform as computed by scipy.ndimage.distance_transform_edt?

—
Reply to this email directly or view it on GitHub
<https://github.com/scikit-image/skimage-demos/pull/4#issuecomment-104061650>
.

**Comment by stefanv** [comment]
I am worried that this part of the tutorial will go right over people's
heads.  Let's give it one more "thinking try", and if we cannot come up
with any ideas over the next day or to, merge it as-is.

**Comment by JDWarner** [comment]
Updated the notebook. I simplified and improved the readability (or split) several dense cells. One of the sections in the costs function was extraneous, and now it's removed.

There is no better way to do this I know of. It does look simpler now. This (95452f4) is the version included in [skimage-tutorials/pulls/17](https://github.com/scikit-image/skimage-tutorials/pull/17).

**Comment by stefanv** [comment]
Great work--since I can't come up with a simpler way, let's use this one.  And you get to explain it to the attendees :)

**Pull request merged**
